// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"exchange-api/internal/midd"
	"exchange-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	//如果要有中间件怎么办
	order := NewOrderHandler(serverCtx)
	orderGroup := r.Group()
	orderGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))
	orderGroup.Post("/order/history", order.History)
	orderGroup.Post("/order/current", order.Current)
	orderGroup.Post("/order/add", order.Add)

}
