// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ucenter-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	//如果要有中间件怎么办
	register := NewRegisterHandler(serverCtx)
	registerRouter := r.Group()
	registerRouter.Post("/uc/register/phone", register.Register)
	registerRouter.Post("/uc/mobile/code", register.SendCode)
}
